name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.head_branch == 'dev' || github.event.workflow_run.head_branch == 'stg')

    steps:
      - name: Print current directory
        run: pwd

      - name: List all files in the current directory
        run: ls -la

      - name: Download build artifacts from CI
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build
        continue-on-error: true

      - name: List downloaded files in .next directory
        run: ls -la .next

      - name: Check if artifacts were downloaded
        id: artifact-check
        run: echo "Artifact exists =${{ steps.download-artifact.outputs.found }}"

      - name: Fail if artifacts are missing
        if: steps.download-artifact.outputs.found != 'true'
        run: |
          echo "No build artifacts found, stopping deployment."
          exit 1

      - name: Deploy to Vercel Preview
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_PREVIEW_TOKEN }}
        run: |
          if [ "${{ github.event.workflow_run.head_branch }}" == "dev" ]; then
            ENVIRONMENT="development"
          elif [ "${{ github.event.workflow_run.head_branch }}" == "stg" ]; then
            ENVIRONMENT="staging"
          fi
          npx vercel --token $VERCEL_TOKEN --scope ${{ secrets.VERCEL_PROJECT_ID }} --env NEXT_PUBLIC_ENV=$ENVIRONMENT --prod=false

  deploy-production:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'

    steps:
      - name: Print current directory
        run: pwd

      - name: List all files in the current directory
        run: ls -la

      - name: Download build artifacts from CI
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build
        continue-on-error: true

      - name: List downloaded files in .next directory
        run: ls -la .next

      - name: Check if artifacts were downloaded
        id: artifact-check
        run: echo "Artifact exists =${{ steps.download-artifact.outputs.found }}"

      - name: Fail if artifacts are missing
        if: steps.download-artifact.outputs.found != 'true'
        run: |
          echo "No build artifacts found, stopping deployment."
          exit 1

      - name: Deploy to Vercel Production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_PROD_TOKEN }}
        run: |
          npx vercel --token $VERCEL_TOKEN --scope ${{ secrets.VERCEL_PROJECT_ID }} --env NEXT_PUBLIC_ENV=production --prod=true
