name: Continuous Integration

on:
  push:
    branches:
      - dev
      - stg
      - main

jobs:
  ci-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-

      - name: Install dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint

      # - name: Run Unit Tests
      #   run: npm run test

      # - name: Upload test results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-results
      #     path: ./test-results

  ci-build:
    name: Build App
    runs-on: ubuntu-latest
    needs: ci-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies from cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-

      - name: Build Next.js app
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: .next
          include-hidden-files: true
