name: Custom Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure branch is up to date
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git diff --exit-code origin/${{ github.event.pull_request.base.ref }} origin/${{ github.event.pull_request.head.ref }}
        continue-on-error: true

      - name: Fail if branch is not up to date
        if: ${{ failure() }}
        run: |
          echo "Branch is not up to date with the base branch."
          exit 1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build Pull Request
        run: npm run build

      - name: Check for security vulnerabilities
        run: npm audit
