name: Manual Preview Deployment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select branch to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stg

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build

      - name: Deploy to Vercel Preview
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_PREVIEW_TOKEN }}
        run: |
          if [ "${{ github.event.inputs.branch }}" == "dev" ]; then
            ENVIRONMENT="development"
          elif [ "${{ github.event.inputs.branch }}" == "stg" ]; then
            ENVIRONMENT="staging"
          fi
          npx vercel --token $VERCEL_TOKEN --scope ${{ secrets.VERCEL_PROJECT_ID }} --env NEXT_PUBLIC_ENV=$ENVIRONMENT --prod=false
