name: Manual Branch Update

on:
  workflow_dispatch:
    inputs:
      source-branch:
        description: "Source branch to merge from"
        required: true
        default: "dev"
      target-branch:
        description: "Target branch to merge into"
        required: true
        default: "stg"

jobs:
  update-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.source-branch }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Checkout target branch
        run: |
          git fetch origin ${{ github.event.inputs.target-branch }}:${{ github.event.inputs.target-branch }}
          git checkout ${{ github.event.inputs.target-branch }}

      - name: Merge source branch into target branch
        run: |
          git merge ${{ github.event.inputs.source-branch }} --no-ff --allow-unrelated-histories || true

      - name: Resolve merge conflicts
        if: failure()
        run: |
          git merge --abort
          echo "Merge conflict detected. Please resolve conflicts manually."
          exit 1

      - name: Push changes
        if: success()
        run: git push origin ${{ github.event.inputs.target-branch }}
